[openssl]
dir = "/a/programFiles/AndroidSDK/openssl/openssl_arm64_v8a"
lib_dir = "${openssl.dir}/lib"
include_dir = "${openssl.dir}/include"

[android]
target = "aarch64-linux-android"
ndk_path = "/a/programFiles/AndroidSDK/Android/Sdk/ndk/29.0.13113456"
toolchain = "${android.ndk_path}/toolchains/llvm/prebuilt/windows-x86_64"

[toolchain]
ar = "${android.toolchain}/bin/llvm-ar"
cc = "${android.toolchain}/bin/clang --target=${android.target}"
as = "${toolchain.cc}"
cxx = "${android.toolchain}/bin/aarch64-linux-android23-clang++ --target=${android.target}"
ld = "${android.toolchain}/bin/ld"
ranlib = "${android.toolchain}/bin/llvm-ranlib"
strip = "${android.toolchain}/bin/llvm-strip"