[env]
#OPENSSL_DIR = {value="A:\\programFiles\\AndroidSDK\\openssl\\openssl_arm64_v8a"}
#LIBCLANG_PATH = { value = "A:\\programFiles\\LLVM\\bin" }
#FFMPEG_DIR = { value = "D:\\flutter_pro\\ffmpeg-4.3\\ffmpeg_install"}