[package]
name = "rust_lib_audio_player"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.6.0"
rodio = {version="^0.20", features =["symphonia-all","default"]}
symphonia = "^0.5"
tokio = { version = "^1", features = ["full"] }
serde = "^1.0"
serde_json = { version = "^1.0", default-features = false, features = ["alloc"] }

[profile.release]
strip=true
lto=true
codegen-units=1
opt-level='z'
panic='abort'